Repository danielfernau/unifi-protect-video-downloader, pull requests merged in 2024-02, with the labels that each got.

#388 Fix downloading smart events
  protect_archiver/downloader/get_motion_event_list.py
Labels: bug, enhancement

#407 Add Python 3.12 support and update Poetry to 1.7.1
  .github/workflows/pythonpackage.yml
  poetry.lock
  pyproject.toml
Labels: dependencies

#409 Add support for environment variables
  protect_archiver/cli/download.py
  protect_archiver/cli/events.py
  protect_archiver/cli/sync.py
Labels: enhancement
